name: cryvault
description: A Flutter crypto wallet.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.13.2
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  bip39: ^1.0.6
  pointycastle: ^3.7.3
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
